import {lazy,Suspense,useEffect,useRef,useState} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useParams,useSearchParams,Link,useNavigate} from 'react-router-dom'
import type {ResearchOutcome} from '../types/research_outcome'
import {api,operation,state} from './api'
import Composer,{Attachments,useAttachments,type ComposerProps} from './ResearchComposer'
import ResearchReport from './ResearchReport'
import './research-experience.css'
const ResearchTrace=lazy(()=>import('./ResearchTrace'))
const terminal=(s:string)=>['completed','failed','cancelled'].includes(s)
export function researchStatus(r:any){
 if(r.task.status==='cancelled')return '已停止'
 if(r.task.status==='running')return '研究中'
 if(['pending','running'].includes(r.interpretation_status))return r.messages?.length?'正在理解补充':'正在理解问题'
 if(r.interpretation_status==='error')return '理解暂未完成'
 return ({queued:'排队中',waiting_user:'需要你补充',completed:'已完成',failed:'研究中断'} as Record<string,string>)[r.task.status]||state(r.task.status)
}
const subjectNames=(r:any)=>r.interpretation?.subjects?.filter((s:any)=>s.role!=='excluded').map((s:any)=>s.mention||s.name).join('、')||(r.input.company==='INDUSTRY'?r.input.scope?.topic:r.input.company)||'识别研究对象中'
const shortTitle=(r:any)=>r.interpretation?.title||r.input.question.replace(/^[*\s]+|[*\s]+$/g,'').split(/[。\n]/)[0].slice(0,72)||'材料研究'
export default function NativeResearch({notify}:ComposerProps){
 const{rid}=useParams();const[params,setParams]=useSearchParams();const[search,setSearch]=useState(''),[filter,setFilter]=useState('all');const client=useQueryClient()
 const{data:requests=[]}=useQuery({queryKey:['research-requests'],queryFn:()=>api('/research/requests'),refetchInterval:5000})
 const{data:r,error}=useQuery({queryKey:['research',rid],queryFn:()=>api('/research/requests/'+rid),enabled:!!rid,refetchInterval:2000})
 const version=params.get('version');const{data:report,error:reportError,isFetching:reportLoading}=useQuery({queryKey:['research-report',rid,version,r?.task?.research?.latest_artifact_version,r?.task?.status],queryFn:()=>api<ResearchOutcome>('/research/requests/'+rid+'/report'+(version?'?version='+version:'')),enabled:!!rid&&(!!r?.task?.research?.latest_artifact_version||r?.task?.status==='completed')&&r?.task?.result?.status!=='collected',refetchInterval:r&&!terminal(r.task.status)?4000:false})
 const{data:artifacts}=useQuery({queryKey:['research-versions',rid,r?.task?.research?.latest_artifact_version],queryFn:()=>api('/research/requests/'+rid+'/artifacts'),enabled:!!rid&&!!report})
 const[disconnected,setDisconnected]=useState(false)
 const tab=params.get('tab')==='report'?'overview':params.get('tab')||'overview'
 function changeTab(value:string){setParams(p=>{if(value==='overview')p.delete('tab');else p.set('tab',value);return p},{replace:true})}
 useEffect(()=>{if(!rid)return;const stream=new EventSource('/api/desk/research/requests/'+rid+'/events');stream.onmessage=e=>{setDisconnected(false);try{client.setQueryData(['research',rid],JSON.parse(e.data))}catch{}};stream.onerror=()=>setDisconnected(true);return()=>stream.close()},[rid,client])
 async function cancel(){try{await api('/research/requests/'+rid+'/cancel',{});client.invalidateQueries({queryKey:['research',rid]})}catch(e){notify(String(e))}}
 if(!rid)return <div className="rx-page rx-home"><header className="rx-home-heading"><span className="rx-eyebrow">PITR / RESEARCH</span><h1>从一个问题，开始研究</h1><p>直接描述问题，或添加需要核对的材料。</p></header><Composer notify={notify} company={params.get('company')||''} question={params.get('question')||''} wikiRef={params.get('wiki_ref')||''}/><section className="rx-history"><div className="rx-section-title"><h2>研究记录 <span>{requests.length}</span></h2><input aria-label="搜索研究记录" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索问题、公司…"/></div><div className="rx-filters" role="group" aria-label="筛选研究记录">{[['all','全部'],['active','进行中'],['attention','需要关注'],['completed','已完成']].map(([id,name])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{name}</button>)}</div><div className="rx-history-list">{[...requests].sort((a:any,b:any)=>(b.updated_at||b.created_at).localeCompare(a.updated_at||a.created_at)).filter((x:any)=>(shortTitle(x)+' '+x.input.question+' '+subjectNames(x)).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='active'&&!terminal(x.task.status)||filter==='attention'&&['waiting_user','failed'].includes(x.task.status)||filter==='completed'&&x.task.status==='completed')).map((x:any)=><Link key={x.id} to={'/research/'+x.id} className="rx-history-item"><span className="rx-history-copy"><b>{shortTitle(x)}</b><small>{subjectNames(x)}{x.input.period?' · '+x.input.period:''}</small></span><span className={'rx-status '+(!terminal(x.task.status)?'rx-status-active':'')}>{researchStatus(x)}</span><time>{(x.updated_at||x.created_at).slice(5,16).replace('T',' ')}</time><span aria-hidden="true">↗</span></Link>)}</div>{!requests.length&&<div className="rx-empty">第一项研究会保存在这里。试着提出你最近想弄清楚的一个问题。</div>}</section></div>
 return <div className="rx-page">{error&&<p className="rx-error" role="alert">研究记录暂时无法加载，正在重试。{String(error)}</p>}{!r?<div className="rx-loading" role="status">正在读取研究记录…</div>:<><header className="rx-record-heading"><div className="rx-breadcrumb"><Link to="/research">研究记录</Link><span>/</span><span>{subjectNames(r)}</span></div><div className="rx-title-line"><h1>{shortTitle(r)}</h1><span className={'rx-status '+(!terminal(r.task.status)?'rx-status-active':'')}>{researchStatus(r)}</span></div><div className="rx-record-meta">{r.task.agent&&<span>{r.task.agent.provider==='claude'?'Claude Code':'Codex'} · {r.task.agent.resolved_model||r.task.agent.model||'本机默认模型'}</span>}<span>{r.interpretation?.time_description||r.input.period||'按问题确定资料范围'}</span><span>{new Date(r.created_at).toLocaleString('zh-CN')}</span><Link to="/research">＋ 新研究</Link>{!terminal(r.task.status)&&<button onClick={cancel}>取消研究</button>}</div><details className="rx-original"><summary>原始问题与上下文</summary><p>{r.original_question||r.input.question||'仅上传材料'}</p>{r.input.snapshot&&<small>已固定财务快照与对应期间</small>}</details></header>
 <>{disconnected&&!terminal(r.task.status)&&r.task.status!=='waiting_user'&&<p className="rx-connection" role="status">实时连接暂时中断，正在自动重连；研究和补充记录已保存。<button onClick={()=>client.invalidateQueries({queryKey:['research',rid]})}>重新读取进展</button></p>}</><div className="rx-revisions">{r.input.parent_request_id&&<Link to={'/research/'+r.input.parent_request_id}>← 查看上一轮研究</Link>}{requests.filter((x:any)=>x.input.parent_request_id===rid).map((x:any)=><Link key={x.id} to={'/research/'+x.id}>继续查看修订 · {researchStatus(x)} →</Link>)}</div>
 {terminal(r.task.status)&&r.interpretation?<details className="rx-completed-scope"><summary>研究范围与调查重点</summary><Understanding request={r}/></details>:<Understanding request={r}/>}
 {r.task.error&&<p className="rx-error" role="alert">{r.task.error}。已保存的研究内容仍可查看，下方补充信息可继续研究。</p>}
 <div className="rx-reading-toolbar"><nav role="tablist" aria-label="研究视图">{[['overview','研究'],['flow','执行流程'],['trace','Trace']].map(([id,name])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>changeTab(id)}>{name}</button>)}</nav>{artifacts?.versions?.length>1&&<label>报告版本<select aria-label="报告版本" value={version||''} onChange={e=>setParams(p=>{e.target.value?p.set('version',e.target.value):p.delete('version');return p})}><option value="">最新版本</option>{artifacts.versions.map((v:any)=><option value={v.version} key={v.version}>版本 {v.version}</option>)}</select></label>}</div>
 {tab==='flow'||tab==='trace'?<Suspense fallback={<p className="rx-loading">读取运行详情…</p>}><ResearchTrace rid={rid} panel={tab} onPanel={changeTab} notify={notify}/></Suspense>:<>{!terminal(r.task.status)&&<Progress request={r} report={report}/>}{report?<><div className="rx-verification"><span>{r.task.status!=='completed'?'阶段草稿 · 尚未完成复核':report.status==='partial'?'已完成 · 部分问题仍缺依据':report.status==='needs_review'?'存在核验问题，需复核':'研究已完成'}</span><details><summary>查看核验状态</summary><p>引用 / 数值完整性：{report.verification.numeric_integrity==='checked'?'已核验':String(report.verification.numeric_integrity||'待核验')}</p><p>独立复核：{String(report.verification.independent_review||'').startsWith('passed')?'已通过':'尚未完成'}</p><Progress request={r} report={report}/><p>人工审核：{report.human_review==='adopted'?'已采纳':report.human_review==='partially_adopted'?'部分判断已采纳':report.human_review==='pending'?'待审核':'尚未采纳'}</p></details></div><ResearchReport report={report} notify={notify}/></>:r.task.result?.status==='collected'?<div className="rx-empty">材料已收录至 Wiki。<Link to="/wiki">查看资料 →</Link></div>:reportError?<p className="rx-error">报告暂时无法加载，已保存的研究记录仍在。请重试读取。</p>:reportLoading?<p className="rx-loading">正在读取已保存报告…</p>:terminal(r.task.status)?<p className="rx-empty">本轮尚未交付报告。可以在下方补充要求并继续研究。</p>:<div className="rx-working-note">回答会在这里逐步形成，引用和数值核对完成后交付报告。</div>}</>}
 <div className="rx-continue-bar"><span>{!terminal(r.task.status)&&r.task.research?.questions?.length?"需要你补充，研究才能继续":"可以随时补充资料、纠正对象或调整重点"}</span><button onClick={()=>{document.getElementById("research-followup")?.scrollIntoView({block:"center"});document.querySelector<HTMLTextAreaElement>("#research-followup textarea")?.focus({preventScroll:true})}}>{terminal(r.task.status)?"继续研究":"补充 / 调整"} ↓</button></div><FollowUp key={rid} request={r} notify={notify}/>
 </>}</div>
}
function Understanding({request:r}:{request:any}){const x=r.interpretation
 if(!x)return ['pending','running'].includes(r.interpretation_status)?<section className="rx-understanding" role="status"><i className="rx-pulse"/><div><b>正在理解你的问题</b><p>识别研究对象、时间范围和需要回答的重点。</p></div></section>:r.interpretation_status==='error'?<p className="rx-error" role="alert">{r.interpretation_error||'暂未完成理解'}。下方可重试或补充名称。</p>:null
 return <section className="rx-understanding"><div className="rx-understanding-main"><span className="rx-eyebrow">本次研究</span><div className="rx-subjects">{x.subjects.filter((s:any)=>s.role!=='excluded').map((s:any)=><span key={s.company_id||s.name} title={s.rationale}>{s.mention||s.name}<small>{s.securities?.map((v:any)=>v.exchange+' '+v.ticker).join(' / ')}{s.role==='reference'?' · 参照':''}</small></span>)}{x.scope_type==='industry'&&<span>{x.topic||'行业问题'}</span>}</div><p>{x.questions.join('；')}</p></div><details><summary>调查重点</summary><ol>{x.plan.map((p:string,i:number)=><li key={i}>{p}</li>)}</ol>{x.assumptions.map((p:string,i:number)=><p key={i}>{p}</p>)}<h3>对象识别依据</h3>{x.subjects.map((s:any)=><p key={s.name}><b>{s.name}</b> · {s.role==='excluded'?'已排除':s.role==='reference'?'参照公司':'研究主体'}<br/>{s.rationale}{s.identity_sources?.map((url:string)=><a key={url} href={url} target="_blank" rel="noreferrer"> 身份依据 ↗</a>)}</p>)}</details></section>
}
function Progress({request:r,report}:{request:any;report?:ResearchOutcome}){const progress=r.task.research?.progress;const items=r.activity?.items||[];const running=!terminal(r.task.status);const coverage=report?.coverage||[]
 return <section className="rx-progress"><div className="rx-progress-line"><span className={'rx-progress-dot '+(running?'active':'')}/><b>{running?(items.find((x:any)=>x.kind==='status')?.text||researchStatus(r)):'研究进展'}</b><span>{r.activity?.reading_count>0?r.activity.reading_count+' 次原件阅读':''}</span>{coverage.length>0&&<span>{coverage.filter(c=>c.status==='answered').length} 项已回答 · {coverage.filter(c=>c.status==='gap').length} 项资料缺口</span>}</div>{progress&&running&&<div className="rx-findings"><small>阶段发现 · 尚待核验</small><p>{progress.findings}</p>{progress.next_steps&&<p className="d-muted">接下来：{progress.next_steps}</p>}</div>}{coverage.length>0&&<details><summary>逐项问题覆盖</summary><ul className="rx-coverage">{coverage.map(c=><li key={c.key}><span>{report?.requirements?.find(q=>q.id===c.key)?.question||c.key}</span><b>{({answered:'已回答',gap:'资料缺口',missing:'待调查',invalid:'待修复'} as any)[c.status]}</b></li>)}</ul></details>}</section>
}
function FollowUp({request:r,notify}:{request:any;notify:(s:string)=>void}){const[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const attachments=useAttachments(notify);const client=useQueryClient(),navigate=useNavigate(),op=useRef(operation()),flight=useRef(false),sent=useRef(''),sentVersion=useRef(0)
 const questions=r.task.research?.questions||[];const clarify=r.task.status==='waiting_user'&&questions.length>0;const latest=r.interpretation
 async function send(value=text){if(flight.current||(!value.trim()&&!attachments.files.length))return;const fingerprint=JSON.stringify([value,attachments.files.map(a=>[a.file.name,a.file.size,a.file.lastModified])]);if(fingerprint!==sent.current){op.current=operation();sent.current=fingerprint;sentVersion.current=r.task.research?.input_version||0}flight.current=true;setBusy(true);setError('');try{const source_ids=await attachments.upload();const next=await api('/research/requests/'+r.id+'/messages',{operation_id:op.current,text:value,source_ids,expected_input_version:sentVersion.current})
  setText('');attachments.clear();op.current=operation();client.invalidateQueries({queryKey:['research',r.id]});client.invalidateQueries({queryKey:['research-requests']});if(next.id!==r.id)navigate('/research/'+next.id)
 }catch(e){setError(String(e))}finally{flight.current=false;setBusy(false)}}
 const pending=r.messages?.filter((m:any)=>!['applied','linked','saved'].includes(m.status))||[]
 return <section id="research-followup" className={'rx-followup '+(clarify?'rx-needs-answer':'')}><header><h2>{clarify?'需要你补充':terminal(r.task.status)?'继续研究':'补充或调整研究'}</h2><span>{terminal(r.task.status)?'原报告保留，继续形成新一轮研究':'当前步骤结束后纳入新的要求'}</span></header>{clarify&&<p className="rx-clarification">{questions[0]}</p>}{clarify&&latest?.options?.length>0&&<div className="rx-options">{latest.options.map((o:string)=><button key={o} disabled={busy} onClick={()=>void send(o)}>{o}</button>)}</div>}
 {r.messages?.length>0&&<details className="rx-message-history" open={pending.length>0}><summary>补充记录 · {r.messages.length}</summary>{r.messages.map((m:any)=><div key={m.id}><p>{m.text||'补充附件'}</p><small>{({received:'已收到 · 正在理解',ready:'待纳入本轮研究',applied:'已纳入研究',saved:'已保存 · 本轮已停止',linked:'已进入关联修订'} as any)[m.status]||m.status}</small>{m.next_request_id&&<Link to={'/research/'+m.next_request_id}>查看后续研究 →</Link>}</div>)}</details>}
 <form onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label={clarify?'澄清回答':'补充研究要求'} disabled={busy} value={text} onChange={e=>{setText(e.target.value);op.current=operation()}} placeholder={clarify?'也可以直接输入你的回答…':'例如：重点看费用投入能否持续，同时核对现金流。'} rows={2}/><div className="rx-composer-tools"><Attachments attachments={attachments} disabled={busy}/><span className="d-spacer"/>{r.interpretation_status==='error'&&<button type="button" disabled={busy} onClick={()=>void send(text||'请按原始问题重新理解并继续。')}>重试理解</button>}<button type="submit" className="primary" disabled={busy||(!text.trim()&&!attachments.files.length)}>{busy?'保存中…':clarify?'保存并继续':terminal(r.task.status)?'继续研究':'发送补充'}</button></div>{error&&<p className="rx-error" role="alert">{error}</p>}</form></section>
}
