import {test,expect} from '@playwright/test'

test('typed evidence, focus, revisions, independent Word retry and history',async({page})=>{
 await page.goto('/research')
 await page.getByRole('link',{name:'离线界面验收：季度研究'}).click()
 const chip=page.getByRole('button',{name:/查看数值依据/}).first()
 await chip.click()
 await expect(page.getByTestId('evidence-rail')).toContainText('Revenue 100.000')
 await page.keyboard.press('Escape')
 await expect(chip).toBeFocused()
 await page.getByRole('button',{name:'修订报告',exact:true}).click()
 await page.getByLabel('报告标题',{exact:true}).fill('修订后的离线报告')
 await page.getByLabel('修订原因',{exact:true}).fill('明确表述')
 await page.getByRole('button',{name:'保存新修订并重新核验'}).click()
 await expect(page.getByRole('heading',{name:'修订后的离线报告',exact:true})).toBeVisible()
 await expect(page.getByLabel('报告版本')).toHaveValue('2')
 const before=await (await page.request.get('/api/v1/runs')).json()
 await page.getByRole('button',{name:'导出 Word',exact:true}).click()
 await page.getByRole('button',{name:'仅重试导出',exact:true}).click()
 await expect(page.getByRole('link',{name:'下载 Word',exact:true})).toBeVisible({timeout:40000})
 const download=page.waitForEvent('download');await page.getByRole('link',{name:'下载 Word',exact:true}).click();expect((await download).suggestedFilename()).toContain('.docx')
 expect((await (await page.request.get('/api/v1/runs')).json()).map((r:any)=>r.id)).toEqual(before.map((r:any)=>r.id))
 await page.getByRole('button',{name:/查看数值依据/}).first().click()
 await expect(page.getByTestId('evidence-rail')).toBeVisible()
 await page.getByLabel('报告版本').selectOption('1')
 await expect(page.getByTestId('evidence-rail')).toHaveCount(0)
 await expect(page.getByRole('heading',{name:'拼多多季度研究',exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'下载 Word',exact:true})).toHaveCount(0)
 const trace=await(await page.request.get('/api/v1/runs/'+before[0].id+'/trace')).json()
 expect(trace.spans.filter((s:any)=>s.kind==='export').map((s:any)=>s.status)).toEqual(['failed','completed'])
 await page.getByRole('radio',{name:'执行流程',exact:true}).click()
 await expect(page.getByTestId('run-graph')).toContainText('生成 Word')
})

test('save a question, cancel and continue through the same command path',async({page})=>{
 await page.goto('/research')
 await page.getByLabel('研究问题',{exact:true}).fill('离线验收：执行恢复路径')
 await page.getByRole('button',{name:'开始研究',exact:true}).click()
 await page.getByRole('button',{name:'取消研究',exact:true}).click()
 await expect(page.getByRole('button',{name:'从检查点继续研究'})).toBeVisible()
 await page.getByRole('button',{name:'从检查点继续研究'}).click()
 await expect(page.getByRole('heading',{name:'离线界面测试报告',exact:true})).toBeVisible()
 await expect(page.getByText('可交付',{exact:true})).toBeVisible()
 await page.getByRole('radio',{name:'执行流程',exact:true}).click()
 await expect(page.getByTestId('run-graph')).toContainText('恢复执行')
})

test('news draft keeps originals and remains experimental',async({page})=>{
 await page.goto('/lab/news')
 await page.getByText('离线示例：跨境履约规则调整，需要重新核对成本假设',{exact:true}).first().click()
 await page.getByRole('button',{name:'深入研究',exact:true}).click()
 await expect(page.getByLabel('研究问题')).toHaveValue(/核对新闻/)
 await expect(page.getByText('资讯实验草稿 · 评分不会作为研究核验结果')).toBeVisible()
 await expect(page.getByText(/选择已有材料 · 已选 1 份/)).toBeVisible()
 await page.getByRole('button',{name:'保存问题',exact:true}).click()
 await expect(page.getByRole('heading',{name:/核对新闻/})).toBeVisible()
})

test('adoption and all derived pages work without legacy routes',async({page})=>{
 const failed:string[]=[];page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=500)failed.push(r.url())})
 await page.goto('/review')
 await page.getByLabel('决定理由：收入规模').fill('人工复核离线夹具')
 await page.getByRole('button',{name:'采纳判断',exact:true}).click()
 await expect(page.getByText('没有待决定的判断。')).toBeVisible()
 await page.goto('/companies/PDD')
 await page.getByRole('link',{name:'知识',exact:true}).click()
 await page.getByRole('link',{name:/收入规模/}).first().click()
 await expect(page.getByRole('heading',{name:'收入规模',exact:true})).toBeVisible()
 for(const path of ['/today','/companies','/maintenance','/settings','/lab/news/settings','/evaluations']){await page.goto(path);await expect(page.locator('h1').first()).toBeVisible()}
 expect(failed).toEqual([])
})

test('mobile evidence sheet closes and returns focus',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/research')
 await page.getByRole('link',{name:'离线界面验收：季度研究'}).click()
 const chip=page.getByRole('button',{name:/查看数值依据/}).first()
 await chip.click();await expect(page.getByTestId('evidence-rail')).toBeVisible()
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await expect(chip).toBeFocused()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true)
})

test('source correction creates new input, continues research and adopts an exact judgment revision',async({page})=>{
 await page.goto('/companies/PDD')
 await page.getByRole('link',{name:'资料',exact:true}).click()
 const original=page.getByRole('heading',{name:'离线界面测试原件',exact:true}).locator('..')
 await original.getByText('来源更正或撤回',{exact:true}).click()
 await original.getByLabel('撤回原因').fill('验收：原公司披露需要更正')
 await original.getByRole('button',{name:'撤回此版本',exact:true}).click()
 await page.locator('input[type=file]').setInputFiles({name:'更正后的原件.txt',mimeType:'text/plain',buffer:Buffer.from('PDD Holdings 2025Q2 GAAP RMB millions. Revenue 120.000')})
 await expect(page.getByRole('heading',{name:'更正后的原件.txt',exact:true})).toBeVisible()
 await page.goto('/research')
 await page.getByRole('link',{name:'离线界面验收：季度研究'}).click()
 await expect(page.getByText(/当前有效性提示/)).toBeVisible()
 await page.getByRole('button',{name:'补充材料与问题',exact:true}).click()
 await page.getByLabel('补充后的研究问题').fill('来源更正后继续研究')
 await page.getByRole('button',{name:'移除此旧版本'}).click()
 await page.getByLabel('更正后的原件.txt · 修订 1').check()
 await page.getByRole('button',{name:'保存新输入修订'}).click()
 await expect(page.getByText('输入修订 2',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'从当前输入研究',exact:true}).click()
 await expect(page.getByRole('heading',{name:'来源更正后的报告',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'查看数值依据：120.000 百万元人民币'})).toBeVisible()
 await page.goto('/review')
 await page.getByLabel('决定理由：收入规模').fill('验收：核对更正后的原件')
 await page.getByRole('button',{name:'采纳判断',exact:true}).click()
 await page.goto('/companies/PDD/knowledge')
 await page.getByRole('link',{name:/收入规模/}).first().click()
 await expect(page.getByText('更正后原件对应的季度收入',{exact:true})).toBeVisible()
 await expect(page.getByText('修订 2',{exact:true})).toBeVisible()
})
