import {test,expect} from '@playwright/test'

test('Slack setup saves credentials privately and validates channel IDs',async({page})=>{
 await page.goto('/settings')
 await expect(page.getByRole('heading',{name:'Slack 接入'})).toBeVisible()
 await expect(page.getByRole('link',{name:'创建个人 Slack 工作区 ↗'})).toHaveAttribute('href',/slack\.com/)
 await expect(page.getByRole('button',{name:'登记已通过'})).toBeDisabled()
 await page.getByLabel('App Token',{exact:true}).fill('xapp-browser-fixture')
 await page.getByLabel('Bot Token',{exact:true}).fill('xoxb-browser-fixture')
 await page.getByLabel('工作区 ID',{exact:true}).fill('T1234567')
 await page.getByLabel('本人用户 ID',{exact:true}).fill('U1234567')
 await page.getByLabel('允许操作的频道 ID',{exact:true}).fill('invalid')
 await page.getByRole('button',{name:'保存 Slack 配置'}).click()
 await expect(page.getByRole('status')).toContainText('频道白名单')
 await page.getByLabel('允许操作的频道 ID',{exact:true}).fill('C1234567')
 await page.getByRole('button',{name:'保存 Slack 配置'}).click()
 await expect(page.getByLabel('Bot Token',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('Bot Token',{exact:true})).toHaveAttribute('placeholder','已保存；留空保留')
 await expect(page.getByText('xoxb-browser-fixture',{exact:true})).toHaveCount(0)
 const manifest=await page.request.get('/api/desk/slack-manifest')
 expect(await manifest.text()).toContain('app_mentions:read')
 expect(await manifest.text()).toContain('files:read')
})

test('Slack connection feedback, test send, delivery recovery and attachment links',async({page})=>{
 let connected=false,retried=false,sentTest=false
 await page.route('**/api/desk/slack',route=>route.fulfill({json:{state:connected?'connected':'disconnected',connected,enabled:connected,error:null,inbox:{},outbox:{},last_received_at:null,last_sent_at:null,connection_count:connected?1:0,live_checks:{}}}))
 await page.route('**/api/desk/slack/connect',route=>{connected=true;return route.fulfill({json:{connected:true}})})
 await page.route('**/api/desk/slack/disconnect',route=>{connected=false;return route.fulfill({json:{connected:false}})})
 await page.route('**/api/desk/slack/check',route=>route.fulfill({json:{ok:true}}))
 await page.route('**/api/desk/slack/test',route=>{sentTest=true;return route.fulfill({json:{status:'queued'}})})
 await page.route('**/api/desk/slack/deliveries',route=>route.fulfill({json:[{id:'test-delivery',kind:'file',channel_id:'C1234567',status:retried?'sent':'delivery_unknown',attempts:1,error:retried?null:'TimeoutError',created:1000}]}))
 await page.route('**/api/desk/slack/deliveries/test-delivery/retry',route=>{retried=true;return route.fulfill({json:{status:'pending'}})})
 await page.route('**/api/desk/slack/attachments',route=>route.fulfill({json:[{id:'attachment_example',file_id:'F1234567',name:'example.txt',status:'ready',size:5,error:null}]}))
 await page.goto('/settings')
 await page.getByRole('button',{name:'检查配置'}).click()
 await expect(page.getByText('Bot 工作区验证通过。请继续连接并检查本人私信与测试频道。')).toBeVisible()
 await page.getByRole('button',{name:'连接 Slack',exact:true}).click()
 await expect(page.getByRole('button',{name:'断开 Slack',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'发送测试消息'}).click()
 await expect.poll(()=>sentTest).toBe(true)
 await page.getByRole('button',{name:'重发',exact:true}).click()
 await expect(page.getByText('如果先前已送达，Slack 中会出现重复内容。',{exact:false})).toBeVisible()
 expect(retried).toBe(false)
 await page.getByRole('button',{name:'已核对，重新发送'}).click()
 await expect.poll(()=>retried).toBe(true)
 await expect(page.getByRole('link',{name:'example.txt ↓'})).toHaveAttribute('href','/api/desk/slack/attachments/attachment_example/file')
 await page.getByRole('button',{name:'断开 Slack',exact:true}).click()
 await expect(page.getByRole('button',{name:'发送测试消息'})).toBeDisabled()
})
