import {test,expect} from '@playwright/test'
const demo=async(request:any)=>(await(await request.get('/api/v1/cases')).json()).find((c:any)=>c.title==='离线演示：平台业务关系与经营变化')

test('observed graph, grouped tools, failure location, exact evidence and replay',async({page,request})=>{
 const c=await demo(request);const [run]=await(await request.get('/api/v1/runs?case_id='+c.id)).json()
 const view=await(await request.get('/api/v1/runs/'+run.id+'/trace')).json()
 expect(view.spans.some((s:any)=>s.kind==='agent')).toBeTruthy()
 expect(view.spans.some((s:any)=>s.parent_id&&s.status==='failed')).toBeTruthy()
 await page.goto('/research/'+c.id+'?tab=flow')
 await expect(page.getByTestId('run-graph')).toBeVisible()
 await page.getByRole('button',{name:'定位第一处 →'}).click()
 await expect(page.getByTestId('trace-inspector')).toContainText('原件块不存在')
 await page.getByRole('button',{name:'返回父调用'}).click()
 await expect(page.getByTestId('trace-inspector')).toContainText('工具调用')
 await page.getByTestId('trace-inspector').getByRole('button',{name:'value.bind · 已结束',exact:true}).click()
 await page.getByRole('button',{name:'查看记录与依据 · 修订 1',exact:true}).click()
 await expect(page.getByTestId('object-details')).toContainText('Revenue 100.000')
 const slider=page.getByRole('slider',{name:'回放事件位置'});await slider.focus();await slider.press('Home')
 await expect(page.getByText('尚无已执行节点。系统不会预画未发生的研究步骤。')).toBeVisible()
 await page.getByRole('button',{name:'返回最新',exact:true}).click()
 await expect(page.locator('.react-flow__node').filter({hasText:'独立复核'}).first()).toBeVisible()
 await page.getByRole('radio',{name:'瀑布',exact:true}).click()
 await expect(page.getByTestId('waterfall')).toBeVisible()
 await page.reload();await expect(page.getByTestId('trace-panel')).toBeVisible()
})

test('company graph, exact revisions, navigation and browser history',async({page})=>{
 await page.goto('/companies/PDD/map')
 await expect(page.getByTestId('company-graph')).toBeVisible()
 await expect(page.locator('.react-flow__node')).toHaveCount(2)
 await page.locator('.react-flow__edge-textbg').first().click()
 await expect(page.getByTestId('evidence-rail')).toContainText('原件描述两家主体的平台业务')
 await expect(page.getByTestId('object-details')).toContainText('原件修订 1')
 await page.keyboard.press('Escape')
 await page.getByRole('link',{name:'数据',exact:true}).click()
 await expect(page.getByRole('img',{name:/数值图表/})).toBeVisible()
 await page.getByRole('button',{name:'查看数值依据：revenue'}).first().click()
 await expect(page.getByTestId('object-details')).toContainText('RMB_mn')
 await page.keyboard.press('Escape')
 await page.goBack();await page.goBack();await page.goBack()
 await expect(page.getByTestId('company-workspace')).toBeVisible()
 await page.goto('/companies/PDD/knowledge')
 await page.getByRole('link',{name:/经营观察模型/}).first().click()
 await expect(page.getByRole('heading',{name:'离线演示：经营观察模型'})).toBeVisible()
 await page.reload();await expect(page.getByRole('heading',{name:'离线演示：经营观察模型'})).toBeVisible()
})

test('mobile trace inspector restores focus and keeps graph reachable',async({page,request})=>{
 await page.setViewportSize({width:390,height:844});const c=await demo(request)
 await page.goto('/research/'+c.id+'?tab=trace')
 const row=page.getByTestId('waterfall').getByRole('row').filter({hasText:'研究与报告'}).first()
 await row.click();await expect(page.getByRole('dialog',{name:'节点检查'})).toBeVisible()
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await expect(row).toBeFocused()
 await page.getByRole('radio',{name:'运行图',exact:true}).click()
 await expect(page.getByTestId('run-graph')).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()
})

test('composer preserves attachments, supports search and IME-safe submission',async({page})=>{
 await page.goto('/research?company=PDD')
 await expect(page.getByRole('combobox',{name:'当前公司',exact:true})).toHaveValue('PDD')
 await page.getByLabel('研究问题',{exact:true}).fill('离线演示：补充附件')
 await page.getByLabel('研究附件',{exact:true}).setInputFiles({name:'补充说明.txt',mimeType:'text/plain',buffer:Buffer.from('Offline UI fixture. No investment conclusion.')})
 await expect(page.getByText('补充说明.txt',{exact:true})).toBeVisible()
 await page.getByLabel('研究问题').dispatchEvent('keydown',{key:'Enter',ctrlKey:true,isComposing:true})
 await expect(page).toHaveURL(/\/research\?company=PDD/)
 await page.getByLabel('搜索研究记录').fill('不存在的研究')
 await expect(page.getByText('没有符合筛选条件的研究。')).toBeVisible()
 await page.getByRole('button',{name:'移除材料 补充说明.txt'}).click()
 await expect(page.getByRole('button',{name:'移除材料 补充说明.txt'})).toHaveCount(0)
})

test('maintenance and settings navigation preserves forms, history and appearance',async({page})=>{
 await page.goto('/settings/agents')
 const model=page.getByLabel('默认模型（留空沿用本机配置）')
 await model.fill('unsaved-offline-choice')
 await page.waitForResponse(r=>r.url().endsWith('/api/v1/settings')&&r.request().method()==='GET')
 await expect(model).toHaveValue('unsaved-offline-choice')
 for(const [path,heading] of [['contact','原件获取'],['documents','Word 编译与渲染'],['appearance','主题与密度']]){
  await page.goto('/settings/'+path);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible()
 }
 await page.getByRole('radio',{name:'深色',exact:true}).click()
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await page.getByRole('radio',{name:'舒适',exact:true}).click()
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-density','comfortable')
 await page.goto('/settings/slack');await expect(page.getByText('Slack', {exact:true}).first()).toBeVisible()
 for(const path of ['jobs','reviews','exports','watch','outbox','backup']){
  await page.goto('/maintenance/'+path);await expect(page.getByTestId('maintenance-page')).toBeVisible()
  await expect(page.getByRole('navigation',{name:'维护导航'}).locator('a[aria-current="page"]')).toHaveCount(1)
 }
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整备份'}).click()
 expect((await download).suggestedFilename()).toBe('pitr-backup.zip')
 await page.reload();await expect(page.getByRole('heading',{name:'备份与恢复',exact:true})).toBeVisible()
 await page.goBack();await expect(page).toHaveURL(/\/maintenance\/outbox/)
 await page.goForward();await expect(page).toHaveURL(/\/maintenance\/backup/)
})

for(const theme of ['light','dark'])for(const width of [1440,390])test(`visual parity surfaces ${theme} ${width}`,async({page,request})=>{
 test.setTimeout(180000)
 const c=await demo(request),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/desk'))errors.push('legacy API request')})
 await page.setViewportSize({width,height:width===390?844:1000})
 await page.addInitScript(t=>localStorage.setItem('pitr.theme',t),theme)
 const routes={today:'/today',research:'/research',report:'/research/'+c.id,flow:'/research/'+c.id+'?tab=flow',waterfall:'/research/'+c.id+'?tab=trace',companies:'/companies',company:'/companies/PDD',knowledge:'/companies/PDD/knowledge',sources:'/companies/PDD/sources',numbers:'/companies/PDD/numbers',map:'/companies/PDD/map',theses:'/companies/PDD/theses',questions:'/companies/PDD/questions',history:'/companies/PDD/history',review:'/review',maintenance:'/maintenance/jobs',settings:'/settings/agents',news:'/lab/news'}
 for(const [name,path] of Object.entries(routes)){
  await page.goto(path);await expect(page.locator('h1').first()).toBeVisible();await page.evaluate(()=>document.fonts.ready)
  if(name==='flow')await expect(page.locator('.react-flow__node').first()).toBeVisible()
  if(name==='map')await expect(page.locator('.react-flow__node')).toHaveCount(2)
  await page.waitForTimeout(['flow','numbers','map'].includes(name)?700:100)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),name).toBeTruthy()
  await expect(page).toHaveScreenshot(`${name}-${theme}-${width}.png`,{fullPage:false})
 }
 expect(errors).toEqual([])
})

test('withdrawn evidence stays visible on historical relationship and report versions',async({page,request})=>{
 const view=await(await request.get('/api/v1/companies/PDD/view')).json(),source=view.sources.find((s:any)=>s.object.title==='离线演示原件：平台业务与关系').object
 const before=new Date().toISOString();const withdrawal=await request.post('/api/v1/sources/'+source.id+'/withdraw',{data:{operation_id:'visual-withdraw',expected_revision:source.revision,reason:'离线验收：来源撤回'}});expect(withdrawal.ok()).toBeTruthy()
 await page.goto('/companies/PDD/map?as_of='+encodeURIComponent(before))
 await expect(page.getByText('依赖有变化',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'离线演示：电商平台同业关系',exact:true}).click()
 await expect(page.getByTestId('evidence-rail')).toContainText('离线验收：来源撤回')
 await expect(page.getByTestId('evidence-rail')).toContainText('原件修订 1')
 const c=await demo(request);await page.goto('/research/'+c.id+'?version=1')
 await expect(page.getByText(/当前有效性提示/)).toBeVisible()
 await expect(page.getByRole('heading',{name:'拼多多季度研究',exact:true})).toBeVisible()
})
