import {lazy,Suspense,useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {api,operation,upload} from '../lib/api'
import {Select,Input,Button,Card,EmptyState,Field,InlineError,useToast} from '../ui'
import {SourceIdentity,Status,useData,key} from './shared'
import {scopeQuery} from './ScopeBar'
import s from '../features/research/research.module.css'
const Directory=lazy(()=>import('./Directory'))
export function Register({onSaved}:{onSaved:()=>void}){const [name,setName]=useState(''),[id,setId]=useState(''),[aliases,setAliases]=useState(''),[domains,setDomains]=useState(''),[market,setMarket]=useState('SEC'),[code,setCode]=useState(''),[candidates,setCandidates]=useState<any[]>([]),[identifiers,setIdentifiers]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),client=useQueryClient();async function save(){setBusy(true);try{await api('/subjects',{operation_id:operation(),identity:id,name,identifiers,aliases:aliases.split(/[，,]/).map(s=>s.trim()).filter(Boolean),official_domains:domains.split(/[，,]/).map(s=>s.trim()).filter(Boolean)});await client.invalidateQueries();onSaved()}catch(e){setError(String(e))}finally{setBusy(false)}}async function discover(){setBusy(true);try{const result=await api<any>('/subjects/discover',{operation_id:operation(),name,market,code});setCandidates(result.candidates);if(!result.candidates.length)setError('官方目录没有匹配项，请核对名称和代码。')}catch(e){setError(String(e))}finally{setBusy(false)}}return <Card className={s.followup}><Field label="官方目录"><Select value={market} onChange={e=>setMarket(e.target.value)}>{['SEC','HKEX','SSE','SZSE','BSE','CNINFO'].map(m=><option key={m}>{m}</option>)}</Select></Field><Field label="证券代码"><Input value={code} onChange={e=>setCode(e.target.value)}/></Field><Button disabled={busy||(!name&&!code)} onClick={discover}>查找主体</Button>{candidates.map((c,i)=><p key={i}><Button onClick={()=>{setId(c.market+':'+c.code);setName(c.name);setAliases(c.aliases.join(','));setIdentifiers({...c.identifiers,[c.market]:c.code})}}>选择 {c.name} · {c.market}:{c.code}</Button></p>)}<Field label="主体标识"><Input placeholder="例如 PDD 或 HKEX:0700" value={id} onChange={e=>setId(e.target.value)}/></Field><Field label="公司名称"><Input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="别名（逗号分隔）"><Input value={aliases} onChange={e=>setAliases(e.target.value)}/></Field><Field label="披露域名（逗号分隔）"><Input value={domains} onChange={e=>setDomains(e.target.value)}/></Field><p className="sub">此登记明确标为人工登记，原件核验状态单独记录。</p>{error&&<InlineError>{error}</InlineError>}<Button disabled={busy||!id.trim()||!name.trim()} onClick={save}>保存公司</Button></Card>}
export function Sources({company,asOf}:{company:string;asOf:string}){const [all,setAll]=useState(false);const {data,error,refetch}=useData<any[]>('/sources?'+scopeQuery(company,asOf)+'&all_revisions='+all),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),{notify}=useToast();async function act(fn:()=>Promise<unknown>){setBusy(true);try{await fn();await refetch()}catch(e){notify(String(e),'danger')}finally{setBusy(false)}}return <><Suspense fallback={<p>载入目录…</p>}><Directory company={company} onImported={()=>refetch()}/></Suspense><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>显示全部原件版本与撤回记录</label><Card className={s.followup}><div className={s.attachRow}><label className={s.attach}>上传原件<input type="file" disabled={busy} onChange={e=>{if(e.target.files?.[0])act(()=>upload('/sources/upload',e.target.files![0],company))}}/></label><Input aria-label="公司原件网址" value={url} onChange={e=>setUrl(e.target.value)} placeholder="公开原件网址"/><Button disabled={busy||!url} onClick={()=>act(()=>api('/sources/fetch',{operation_id:operation(),url,subjects:[company]}))}>获取原件</Button></div></Card>{error&&<InlineError>{String(error)}</InlineError>}{data?.map(src=><SourceCard key={key(src)} source={src} refresh={()=>refetch()}/>)}{data?.length===0&&<EmptyState>暂无原件。</EmptyState>}</>}
function SourceCard({source,refresh}:{source:any;refresh:()=>void}){const [reason,setReason]=useState(''),[error,setError]=useState('');async function withdraw(){try{await api('/sources/'+source.id+'/withdraw',{operation_id:operation(),expected_revision:source.revision,reason});refresh()}catch(e){setError(String(e))}}return <Card className={s.railBody}><h3>{source.title}</h3><p className="sub">修订 {source.revision} · {source.media_type} · <SourceIdentity role={source.source_role}/></p><Status value={source.current_validity.status}/><a href={`/api/v1/sources/${source.id}/revisions/${source.revision}/original`} target="_blank" rel="noreferrer">打开不可变原件</a><details><summary>来源更正或撤回</summary><p className="sub">同一网址重新获取会保存新版本，并提示受影响的研究。</p><Input aria-label="撤回原因" value={reason} onChange={e=>setReason(e.target.value)} placeholder="撤回原因"/><Button disabled={!reason.trim()} onClick={withdraw}>撤回此版本</Button>{error&&<InlineError>{error}</InlineError>}</details></Card>}
