import {useState} from 'react'
import {api,operation} from '../lib/api'
import {Button,Card,Field,InlineError} from '../ui'
import {useData} from './shared'
export default function Directory({company,onImported}:{company:string;onImported:()=>void}){
 const {data}=useData('/source-adapters'),[adapter,setAdapter]=useState('SEC'),[since,setSince]=useState(''),[until,setUntil]=useState(''),[urls,setUrls]=useState(''),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <Card><details><summary>从官方披露目录或历史存档查找原件</summary><Field label="目录"><select value={adapter} onChange={e=>setAdapter(e.target.value)}>{data?.items.map((a:any)=><option key={a.name}>{a.name}</option>)}</select></Field><Field label="起始日期"><input type="date" value={since} onChange={e=>setSince(e.target.value)}/></Field><Field label="截止日期"><input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></Field>{['URL_WATCH','ARCHIVE'].includes(adapter)&&<Field label="原件网址（每行一项）"><textarea value={urls} onChange={e=>setUrls(e.target.value)}/></Field>}<Button disabled={busy} onClick={()=>act(async()=>setResult(await api('/sources/discover',{operation_id:operation(),subject:company,adapter,since,until,urls:urls.split('\n').filter(Boolean)})))}>查找原件</Button>{error&&<InlineError>{error}</InlineError>}{result?.needs_identity_confirmation&&<p>目录未唯一匹配公司。请核对主体名称与证券代码后重试；不会自动绑定其他公司的材料。</p>}{result?.items?.map((item:any,index:number)=><div key={index}><p>{item.title} · {item.published_at||item.published||'时间待核对'}</p><Button size="sm" disabled={busy} onClick={()=>act(async()=>{await api('/sources/discovery-fetch',{operation_id:operation(),discovery_id:result.id,index});onImported()})}>保存此原件</Button></div>)}{result&&!result.items?.length&&!result.needs_identity_confirmation&&<p>此范围没有目录条目。</p>}</details></Card>
}
