import {lazy,Suspense,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {useQueryClient} from '@tanstack/react-query'
import {api,operation} from '../lib/api'
import {Textarea,Badge,Button,Card,CardHeader,EmptyState,Field,Input,InlineError,Loading,Seg} from '../ui'
import {Status,useData,Pending,key} from './shared'
import app from '../app/app.module.css'
import s from '../features/review/review.module.css'
const ObjectDetails=lazy(()=>import('./ObjectDetails'))
export default function Review(){
 const {data,error}=useData<any[]>('/review',5000),{'*':identity}=useParams(),[params,setParams]=useSearchParams(),[query,setQuery]=useState('')
 const filter=params.get('status')||'pending'
 if(!data)return <Pending error={error}/>
 const items=data.filter(g=>(filter==='all'||g.status===filter)&&g.title.includes(query)),selected=items.find(g=>g.id===identity)||items[0]
 return <div className={app.page} data-testid="review-page"><header className={app.pageHead}><h1 className="display">审核判断</h1><span className="sub">核对证据，决定哪些判断进入持续研究知识</span></header><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Seg label="审核状态" value={filter} onChange={value=>setParams({status:value})} options={[{value:'pending',label:'待决定 '+data.filter(g=>g.status==='pending').length},{value:'adopt',label:'已采纳'},{value:'reject',label:'未采纳'},{value:'all',label:'全部记录'}]}/><Input aria-label="筛选审核判断" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索判断…" style={{width:240,marginLeft:'auto'}}/></div>{items.length?<div className={s.layout}><Card className={s.queue}><CardHeader title="审核队列"><span className="mono muted" style={{marginLeft:'auto'}}>{items.length}</span></CardHeader><div className={s.queueList}>{items.map(g=><Link key={g.id} className={s.item} aria-current={selected?.id===g.id?'page':undefined} to={'/review/'+g.id+'?status='+filter}><Status value={g.status}/><div><b>{g.title}</b><p>{g.targets.length>1?`${g.targets.length} 项依赖判断 · 原子采纳`:'可独立采纳'} · 报告 r{g.report?.revision}</p></div></Link>)}</div></Card><div className={s.detail}>{selected&&<Decision key={selected.id} group={selected}/>}</div></div>:<Card><EmptyState>{filter==='pending'?'没有待决定的判断。':'没有符合筛选条件的判断。'}</EmptyState></Card>}</div>
}
function Decision({group}:{group:any}){
 const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<any>(null),client=useQueryClient()
 async function decide(action:string){setBusy(true);try{await api('/review/'+group.id+'/decisions',{operation_id:operation(),expected_revision:group.revision,action,reason});await client.invalidateQueries()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <><div><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:10}}><Status value={group.status}/><Status value={group.current_validity.status}/><Badge>报告修订 {group.report?.revision}</Badge></div><h2 className="display" style={{fontSize:24}}>{group.title}</h2><p className="sub" style={{marginTop:8}}>{group.reason}</p></div><div className={s.verify}>{group.checks?.map((c:any)=><div key={c.id}><b>{c.name==='independent'?'独立复核':'内容与引用'}</b><Status value={c.status}/></div>)}</div>{group.objects.map((o:any)=><Card key={key(o)} className={s.adopt}><h3>{o.title}</h3><p style={{fontSize:15,lineHeight:1.85}}>{o.statement||o.rationale}</p>{o.alternative&&<p className="sub">替代解释：{o.alternative}</p>}{o.limitations?.map((v:string,i:number)=><p key={i} className="sub">{v}</p>)}<Button size="sm" onClick={()=>setSelected(selected?.id===o.id?null:o)}>查看证据与依赖 · 修订 {o.revision}</Button></Card>)}{selected&&<Card><Suspense fallback={<Loading/>}><ObjectDetails reference={selected}/></Suspense></Card>}{group.report&&<Link to={'/research/'+group.case_id+'?run='+group.run_id+'&version='+group.report.revision}>阅读报告引用 · 修订 {group.report.revision} →</Link>}{group.status==='pending'&&<Card className={s.adopt}><Field label="决定理由"><Textarea aria-label={'决定理由：'+group.title} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="记录你的判断与依据…"/></Field>{error&&<InlineError>{error}</InlineError>}<div style={{display:'flex',gap:8}}><Button variant="primary" disabled={busy||!reason.trim()} onClick={()=>decide('adopt')}>采纳{group.targets.length>1?'整组判断':'判断'}</Button><Button disabled={busy||!reason.trim()} onClick={()=>decide('reject')}>不采纳</Button></div></Card>}</>
}
