import {useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {Badge,Button,Card,CardHeader,Dot,EmptyState,Icon,Seg,Table} from '../ui'
import {useCompany} from '../app/company'
import {relativeTime} from '../lib/format'
import {Status,useData,Pending} from './shared'
import app from '../app/app.module.css'
import s from '../features/today/today.module.css'
export default function Today(){
 const navigate=useNavigate()
 const {data,error}=useData('/today',5000),{companies}=useCompany(),[filter,setFilter]=useState('all')
 if(!data)return <Pending error={error}/>
 const today=new Date(),title=(r:any)=>data.cases.find((c:any)=>c.id===r.case_id)?.title||'查看研究记录'
 const groups=[{id:'decide',title:'需要你回答',hint:'补充上下文，继续推进研究',tone:'warn' as const,items:data.runs.filter((r:any)=>r.status==='waiting_user').map((r:any)=>({id:r.id,title:title(r),detail:r.questions.join('；'),status:r.status,at:r.updated_at,href:'/research/'+r.case_id}))},{id:'active',title:'正在推进的研究',hint:'进度来自实际执行记录',tone:'accent' as const,items:data.runs.filter((r:any)=>['queued','running'].includes(r.status)).map((r:any)=>({id:r.id,title:title(r),detail:r.stage==='reviewing'?'独立复核中':'研究与材料核查',status:r.status,at:r.updated_at,href:'/research/'+r.case_id}))},{id:'read',title:'可以阅读的报告',hint:'报告检查与人工采纳单独展示',tone:'ok' as const,items:data.runs.filter((r:any)=>r.report).map((r:any)=>({id:r.id,title:title(r),detail:r.error,status:r.status,at:r.updated_at,href:'/research/'+r.case_id}))},{id:'adopt',title:'待采纳',hint:'独立判断分别决定，依赖判断一起采纳',tone:'accent' as const,items:data.reviews.map((g:any)=>({id:g.id,title:g.title,detail:g.reason,status:g.status,at:g.created_at,href:'/review/'+g.id}))},{id:'alerts',title:'来源变化与执行异常',hint:'查明影响范围，再继续相关研究',tone:'danger' as const,items:[...data.changes.map((c:any)=>({id:c.id+'@'+c.revision,title:c.title,detail:c.reason,status:c.status,at:c.updated_at,href:c.case_id?'/research/'+c.case_id:'/companies'})),...data.runs.filter((r:any)=>['failed','cancelled','budget_exhausted'].includes(r.status)).map((r:any)=>({id:r.id,title:title(r),detail:r.error,status:r.status,at:r.updated_at,href:'/research/'+r.case_id}))]}]
 return <div className={app.page} data-testid="today-page"><header className={app.pageHead}><h1 className="display">今日</h1><span className="sub">{today.getMonth()+1} 月 {today.getDate()} 日 · {data.reviews.length} 项判断待采纳</span><span className={app.spacer}/><Button variant="primary" icon="plus" onClick={()=>navigate('/research')}>开始研究</Button></header><Seg label="今日筛选" value={filter} onChange={setFilter} options={[{value:'all',label:'全部'},...groups.map(g=>({value:g.id,label:g.title+' '+g.items.length}))]}/><div className={s.grid}><div className={s.col}>{groups.filter(g=>filter==='all'||g.id===filter).map(g=>g.items.length>0?<Card key={g.id}><CardHeader title={<><Dot tone={g.tone}/>{g.title}</>}><span className="sub">{g.hint}</span><span className="mono muted" style={{marginLeft:'auto'}}>{g.items.length}</span></CardHeader>{g.items.map((i:any)=><Link to={i.href} key={i.id} className={s.item}><Status value={i.status}/><div className={s.body}><b>{i.title}</b>{i.detail&&<p>{i.detail}</p>}</div><span className={s.when}>{relativeTime(i.at)}</span><Icon name="arrow" size={14}/></Link>)}</Card>:filter!=='all'?<Card key={g.id}><EmptyState>当前没有{g.title}的事项。</EmptyState></Card>:null)}{groups.every(g=>!g.items.length)&&<Card><EmptyState>现在没有需要你处理的事。研究进度和知识变化会保存在这里。</EmptyState></Card>}</div><aside className={s.col}><Card><CardHeader title="覆盖公司"><Link to="/companies" style={{marginLeft:'auto',fontSize:12}}>全部公司 →</Link></CardHeader><Table><tbody>{companies.slice(0,8).map(c=><tr key={c.company}><td><Link to={'/companies/'+encodeURIComponent(c.company)}><b className="mono">{c.company}</b></Link></td><td>{c.name}</td></tr>)}</tbody></Table>{!companies.length&&<EmptyState>还没有登记公司。</EmptyState>}</Card><Card><CardHeader title="资讯实验室"><Badge>Lab</Badge></CardHeader><Link to="/lab/news" className={s.item}><div className={s.body}><b>发现值得继续研究的变化</b><p>从新闻原件生成研究草稿，评分独立保留。</p></div><Icon name="arrow"/></Link></Card></aside></div></div>
}
