import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react'
import {Link,NavLink,useParams,useSearchParams} from 'react-router-dom'
import {useCompany} from '../../app/company'
import {Badge,Button,Card,CardHeader,EmptyState,Input,InlineError,Loading} from '../../ui'
import {dateTime,relativeTime} from '../../lib/format'
import {key,Pending,SourceIdentity,Status,useData} from '../../workbench/shared'
import {Sources} from '../../workbench/CompanyInputs'
import ScopeBar,{scopeQuery} from '../../workbench/ScopeBar'
import {EvidenceRail} from '../research/EvidenceRail'
import type {CompanyView,Ref,Assertion,ModelRevision,CurrentValidity} from '../../types/company_view'
import s from './company.module.css'
const CompanyGraph=lazy(()=>import('./RelationshipGraph'))
const Numbers=lazy(()=>import('./Numbers'))
const ObjectDetails=lazy(()=>import('../../workbench/ObjectDetails'))
const tabs=[['','概览'],['knowledge','知识'],['sources','资料'],['numbers','数据'],['map','产业链'],['theses','判断与模型'],['questions','问题'],['history','历史']]
export default function CompanyShell(){
 const {company='', '*':path=''}=useParams(),{setCompany}=useCompany(),[params,setParams]=useSearchParams(),[query,setQuery]=useState(''),trigger=useRef<HTMLElement|null>(null)
 const parts=path.split('/'),tab=parts[0]||'',asOf=params.get('as_of')||'',base='/companies/'+encodeURIComponent(company),suffix=asOf?'?as_of='+encodeURIComponent(asOf):''
 const {data:view,error}=useData<CompanyView>('/companies/'+encodeURIComponent(company)+'/view?'+scopeQuery(company,asOf),5000)
 const {data:results}=useData<any[]>('/search?'+scopeQuery(company,asOf)+'&q='+encodeURIComponent(query))
 useEffect(()=>{if(view)setCompany(company)},[view?.subject.id,company,setCompany])
 const selected=params.get('object'),requested=selected?{id:selected.slice(0,selected.lastIndexOf('@')),revision:Number(selected.slice(selected.lastIndexOf('@')+1))}:null
 const visibleRefs=view?[...view.knowledge.map(k=>k.object),...view.values.map(v=>v.object),...view.sources.map(v=>v.object),...view.reports,...view.history.map(h=>h.ref)]:[]
 const reference=requested&&visibleRefs.some(r=>key(r)===key(requested))?requested:null
 const select=useCallback((ref:Ref|null)=>{if(ref)trigger.current=document.activeElement as HTMLElement;setParams(p=>{const n=new URLSearchParams(p);if(ref)n.set('object',key(ref));else n.delete('object');return n})},[setParams])
 if(!view)return <Pending error={error}/>
 const item=parts[1]?view.knowledge.find(k=>k.object.id===decodeURIComponent(parts[1])):null
 return <div className={s.shell} data-testid="company-workspace"><header className={s.header}><div className={s.crumbs}><Link to="/companies">公司</Link><span>/</span><span>{view.subject.name}</span></div><div className={s.titleRow}><h1 className="display">{view.subject.name} <small>{company}</small></h1><Badge>{view.subject.status==='verified'?'身份已核实':view.subject.status==='manual'?'人工登记':'待识别'}</Badge><span style={{flex:1}}/><Link to={'/research?company='+encodeURIComponent(company)+(asOf?'&as_of='+encodeURIComponent(asOf):'')}>提出研究问题 →</Link></div><div className={s.meta}><span className="sub">{view.subject.aliases.join(' · ')}</span><span style={{flex:1}}/><Input aria-label="检索材料与知识" placeholder="在这家公司的材料与知识中检索…" value={query} onChange={e=>setQuery(e.target.value)} style={{width:320,height:30}}/></div><nav className={s.subnav} aria-label="公司页面">{tabs.map(([path,label])=><NavLink key={path} end={!path} to={base+(path?'/'+path:'')+suffix}>{label}</NavLink>)}</nav></header>
 <div className={s.body}>{!view.subject_at_time&&<p className={s.timeNote}>该时点尚无主体登记记录；页头使用当前名称，材料与知识仍按指定时点筛选。</p>}<details><summary className="sub" style={{cursor:'pointer'}}>{asOf?'历史时点 · '+asOf.replace('T',' '):'当前资料与已采纳判断'} · 调整资料截止时间</summary><ScopeBar asOf={asOf} onChange={value=>setParams(p=>{const n=new URLSearchParams(p);if(value)n.set('as_of',value);else n.delete('as_of');n.delete('object');return n})}/></details>
 {query&&<Card><CardHeader title={`搜索结果 · ${results?.length||0}`}/>{results?.map(r=><button type="button" className={s.sourceRow} style={{width:'100%',textAlign:'left'}} key={key(r)} onClick={()=>select(r)}><div><b>{r.title}</b><p className="sub">{r.snippet}</p></div></button>)}{!results?.length&&<EmptyState>当前范围没有匹配结果。</EmptyState>}</Card>}
 {requested&&!reference&&<InlineError>此记录版本不在当前公司与时点范围内。</InlineError>}
 <div className={reference?s.evidenceLayout:undefined}><main className={s.main}>
 {!tab&&<Overview view={view} base={base} suffix={suffix} select={select}/>}
 {tab==='knowledge'&&<div className={s.knowledge}><aside className={s.dir}><div className={s.layer}><b>已采纳知识 <small>{view.knowledge.length}</small></b>{view.knowledge.map(k=><NavLink className={s.dirLink} to={base+'/knowledge/'+encodeURIComponent(k.object.id)+suffix} key={key(k.object)}><span>{k.object.title}</span><small>r{k.object.revision}</small></NavLink>)}</div></aside><div className={s.main}>{item?<Knowledge object={item.object} validity={item.current_validity} asOf={asOf} select={select}/>:view.knowledge.length?<div className={s.pageGrid}>{view.knowledge.map(k=><Card key={key(k.object)} className={s.pageCard}><Link to={base+'/knowledge/'+encodeURIComponent(k.object.id)+suffix}><b>{k.object.title}</b></Link><p>{'statement' in k.object?k.object.statement:k.object.rationale}</p><Status value={String(k.current_validity.status)}/></Card>)}</div>:<EmptyState>研究中的判断经过人工采纳后，出现在知识目录。</EmptyState>}</div></div>}
 {tab==='sources'&&(parts[1]?<ScopedSource view={view} identity={parts[1]} revision={Number(params.get('revision'))||null}/>:<Sources company={company} asOf={asOf}/>)}
 {tab==='numbers'&&<Suspense fallback={<Loading>载入数据视图…</Loading>}><Numbers values={view.values} onSelect={select}/></Suspense>}
 {tab==='map'&&<Suspense fallback={<Loading>载入关系图…</Loading>}><CompanyGraph company={view.subject} items={view.knowledge} onSelect={select}/></Suspense>}
 {tab==='theses'&&<>{view.knowledge.map(k=><Knowledge key={key(k.object)} object={k.object} validity={k.current_validity} asOf={asOf} select={select}/>)}{!view.knowledge.length&&<EmptyState>还没有采纳的判断或模型。<Link to="/review">打开审核队列 →</Link></EmptyState>}</>}
 {tab==='questions'&&<Card><CardHeader title="研究问题"><Link to={'/research?company='+encodeURIComponent(company)+(asOf?'&as_of='+encodeURIComponent(asOf):'')}>新问题 →</Link></CardHeader>{view.cases.map(c=><Link to={'/research/'+c.id} className={s.sourceRow} key={c.id}><div><b>{c.title}</b><p className="sub">输入修订 {c.input.revision} · {relativeTime(c.updated_at)}</p></div></Link>)}{!view.cases.length&&<EmptyState>从一个关于这家公司的问题开始。</EmptyState>}</Card>}
 {tab==='history'&&<Card><CardHeader title="研究与知识历史"/><div>{view.history.map((row:any,i:number)=><div className={s.logRow} key={i}><time>{dateTime(row.at)}</time><span>{{source:'原件保存',report:'报告修订',decision:'人工决定'}[row.kind as string]||row.kind} · r{row.ref.revision}</span><div>{row.case_id?<Link to={'/research/'+row.case_id+'?run='+row.run_id+'&version='+row.ref.revision}>{row.title}</Link>:<Button variant="ghost" size="sm" onClick={()=>select(row.ref)}>{row.title||'查看决定记录'}</Button>}</div></div>)}</div>{!view.history.length&&<EmptyState>材料、报告修订与采纳决定会保留在这里。</EmptyState>}</Card>}
 {tab==='ask'&&<Card className={s.current}><h2>研究这家公司</h2><Link to={'/research?company='+encodeURIComponent(company)+(asOf?'&as_of='+encodeURIComponent(asOf):'')}>打开研究工作台 →</Link></Card>}
 </main><EvidenceRail open={!!reference} onClose={()=>select(null)} title="记录与准确版本的证据" returnTo={trigger}>{reference&&<Suspense fallback={<Loading/>}><ObjectDetails key={key(reference)} reference={reference}/></Suspense>}</EvidenceRail></div>
 </div></div>
}
function Knowledge({object:o,validity,select,asOf}:{object:Assertion|ModelRevision;validity:CurrentValidity;asOf:string;select:(r:Ref)=>void}){return <Card className={s.current}><div className={s.meta}><Badge>修订 {o.revision}</Badge><Status value={String(validity.status)}/><Badge>{'assumptions' in o?'模型':'已采纳判断'}</Badge></div><h2>{o.title}</h2><p>{'statement' in o?o.statement:o.rationale}</p>{!!validity.reason&&<p className="sub">当前有效性提示：{String(validity.reason)}</p>}{'alternative' in o&&o.alternative&&<p className="sub">替代解释：{o.alternative}</p>}<div className={s.actions}><Button size="sm" onClick={()=>select(o)}>查看证据与依赖</Button><Link to={'/research?question='+encodeURIComponent('继续核查：'+o.title)+'&knowledge='+encodeURIComponent(key(o))+(asOf?'&as_of='+encodeURIComponent(asOf):'')}>继续研究此判断 →</Link></div></Card>}
function Overview({view,base,suffix,select}:{view:CompanyView;base:string;suffix:string;select:(r:Ref)=>void}){const current=view.knowledge.slice(0,4);return <><Card className={s.tiles}>{[['固定原件',view.sources.length,'sources'],['已采纳知识',view.knowledge.length,'knowledge'],['可追溯数值',view.values.length,'numbers'],['研究报告',view.reports.length,'history']].map(([label,count,path])=><Link key={label} className={s.tile} to={base+'/'+path+suffix}><span className="sub">{label}</span><b className="mono">{count}</b></Link>)}</Card><div className={s.overview}><Card className={s.current}><h3>当前认识</h3>{current.length?current.map(k=><section key={key(k.object)}><Button variant="ghost" onClick={()=>select(k.object)}><b>{k.object.title}</b></Button><p>{'statement' in k.object?k.object.statement:k.object.rationale}</p><Status value={String(k.current_validity.status)}/></section>):<div className={s.unwritten}><b>这家公司的研究尚在起点</b><p className="sub">上传原件并发起研究，经过复核与人工采纳的判断将沉淀在这里。</p></div>}<div className={s.foot}><Link to={base+'/knowledge'+suffix}>阅读全部知识 →</Link><Link to={base+'/map'+suffix}>查看产业关系 →</Link></div></Card><div className={s.main}><Card><CardHeader title="最近的研究"/>{view.cases.slice(0,5).map(c=><Link key={c.id} className={s.sourceRow} to={'/research/'+c.id}><div><b>{c.title}</b><p className="sub">{relativeTime(c.updated_at)}</p></div></Link>)}{!view.cases.length&&<EmptyState>还没有研究记录。</EmptyState>}</Card><Card><CardHeader title="最近的材料"/>{view.sources.slice(0,4).map(({object:o,current_validity:v})=><Link key={key(o)} className={s.sourceRow} to={base+'/sources/'+o.id+'?revision='+o.revision+(suffix?'&'+suffix.slice(1):'')}><div><b>{o.title}</b><p className="sub">修订 {o.revision} · {relativeTime(o.created_at)}</p><SourceIdentity role={o.source_role}/><Status value={String(v.status)}/></div></Link>)}</Card></div></div></>}

function ScopedSource({view,identity,revision}:{view:CompanyView;identity:string;revision:number|null}){const source=view.sources.find(s=>s.object.id===identity&&(!revision||s.object.revision===revision));return source?<Suspense fallback={<Loading/>}><ObjectDetails reference={source.object}/></Suspense>:<EmptyState>此原件版本不在当前公司与时点范围内。</EmptyState>}
