import {useEffect,useMemo,useState} from 'react'
import {ReactFlow,ReactFlowProvider,Background,Controls,Handle,Position,type NodeProps,type Node,type Edge} from '@xyflow/react'
import ELK from 'elkjs/lib/elk.bundled.js'
import '@xyflow/react/dist/style.css'
import type {KnowledgeItem,Subject,Ref,Assertion} from '../../types/company_view'
import {Badge,Button,Card,CardHeader,EmptyState,Input} from '../../ui'
import {token,useThemeVersion} from '../../lib/tokens'
import {Status,key} from '../../workbench/shared'
import s from '../research/trace/trace.module.css'
const elk=new ELK(),maturity:Record<string,string>={proposed:'拟议',announced:'已宣布',in_operation:'已开展',ended:'已结束',uncertain:'不确定'}
type Entity=Node<{label:string;active:boolean;count:number},'entity'>
function EntityNode({data}:NodeProps<Entity>){return <div className={s.node} style={{width:220,padding:14,borderColor:data.active?'var(--accent)':'var(--line)'}}><Handle type="target" position={Position.Left} style={{opacity:0}}/><b>{data.label}</b><p className="sub">{data.count} 项已采纳关系</p><Handle type="source" position={Position.Right} style={{opacity:0}}/></div>}
const nodeTypes={entity:EntityNode}
export default function RelationshipGraph({company,items,onSelect}:{company:Subject;items:KnowledgeItem[];onSelect:(ref:Ref)=>void}){
 const theme=useThemeVersion(),[query,setQuery]=useState(''),[focus,setFocus]=useState(''),[layout,setLayout]=useState<{signature:string;positions:Record<string,{x:number;y:number}>}>({signature:'',positions:{}})
 const relations=items.filter((k):k is KnowledgeItem&{object:Assertion}=>'kind' in k.object&&k.object.kind==='relationship').filter(k=>(k.object.title+' '+k.object.statement+' '+JSON.stringify(k.object.relation)).toLowerCase().includes(query.toLowerCase()))
 const ids=[...new Set(relations.flatMap(k=>[String(k.object.relation.from),String(k.object.relation.to)]))],signature=relations.map(k=>key(k.object)).join('|')
 const positions=layout.signature===signature?layout.positions:{}
 useEffect(()=>{let live=true;elk.layout({id:'root',layoutOptions:{'elk.algorithm':'layered','elk.direction':'RIGHT','elk.spacing.nodeNode':'55','elk.layered.spacing.nodeNodeBetweenLayers':'180'},children:ids.map(id=>({id,width:220,height:76})),edges:relations.map(k=>({id:key(k.object),sources:[String(k.object.relation.from)],targets:[String(k.object.relation.to)]}))}).then(g=>{if(live)setLayout({signature,positions:Object.fromEntries((g.children||[]).map(n=>[n.id,{x:n.x||0,y:n.y||0}]))})});return()=>{live=false}},[signature])
 const nodes:Entity[]=ids.map(id=>({id,type:'entity',position:positions[id]||{x:0,y:0},data:{label:id===company.id?company.name:id,active:id===focus||id===company.id,count:relations.filter(k=>k.object.relation.from===id||k.object.relation.to===id).length}}))
 const edges:Edge[]=useMemo(()=>relations.map(k=>({id:key(k.object),source:String(k.object.relation.from),target:String(k.object.relation.to),type:'smoothstep',label:`${k.object.relation.type} · ${maturity[String(k.object.relation.maturity)]||'未注明成熟度'}`,style:{stroke:token(k.current_validity.status==='available'?'accent':'warn'),strokeWidth:1.7,strokeDasharray:k.current_validity.status==='available'?undefined:'5 4'},labelStyle:{fontSize:12,fill:token('ink-2')},labelBgStyle:{fill:token('surface')},markerEnd:{type:'arrowclosed',color:token('accent')},ariaLabel:k.object.title,focusable:true,domAttributes:{onKeyDown:(event)=>{if(event.key==='Enter'){event.preventDefault();onSelect(k.object)}}}})),[signature,theme,JSON.stringify(items.map(i=>i.current_validity)),onSelect])
 const filtered=relations.filter(k=>!focus||k.object.relation.from===focus||k.object.relation.to===focus)
 return <><Card><CardHeader title="产业关系"><Input aria-label="筛选关系" placeholder="主体、关系或判断…" value={query} onChange={e=>setQuery(e.target.value)} style={{marginLeft:'auto',width:240}}/></CardHeader><div className={s.graph} style={{border:0,borderRadius:0}} data-testid="company-graph">{nodes.length?<ReactFlowProvider><ReactFlow key={signature+Object.keys(positions).length} nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.3,maxZoom:1}} minZoom={.25} maxZoom={1.8} nodesDraggable={false} nodesConnectable={false} onNodeClick={(_,n)=>setFocus(focus===n.id?'':n.id)} onEdgeClick={(_,e)=>{const item=relations.find(k=>key(k.object)===e.id);if(item)onSelect(item.object)}} proOptions={{hideAttribution:true}}><Background gap={22} color={token('line')}/><Controls showInteractive={false}/></ReactFlow></ReactFlowProvider>:<EmptyState>没有符合条件的已采纳关系。研究中提出、复核并采纳关系后会显示在这里。</EmptyState>}</div></Card><p className="sub">点击节点聚焦关联判断，点击连线打开准确版本的证据。来源身份、关系成熟度和当前有效性分别记录。</p>{focus&&<Button size="sm" onClick={()=>setFocus('')}>清除主体筛选 · {focus}</Button>}{filtered.map(k=><Card key={key(k.object)} style={{padding:16}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><Button variant="ghost" onClick={()=>onSelect(k.object)}>{k.object.title}</Button><Badge>{maturity[String(k.object.relation.maturity)]||'未注明成熟度'}</Badge><Status value={String(k.current_validity.status)}/><span className="sub">修订 {k.object.revision}</span></div><p>{k.object.statement}</p><p className="sub">{String(k.object.relation.semantic_basis||'')}</p></Card>)}</>
}
