import {useRef,useState} from 'react'
import type {ReportView,Paragraph} from '../../types/report_view'
import {api,operation} from '../../lib/api'
import {Select,Textarea,Input,Button,Card,Field,InlineError} from '../../ui'
import {key} from '../../workbench/shared'
import s from './research.module.css'
type Inline=Paragraph['inlines'][number]
const text=(spans:Inline[])=>spans.map(s=>s.type==='text'?s.text:`{{${s.type==='value'?'数值':'引用'}:${key(s.ref)}}}`).join('')
function parse(value:string,report:ReportView):Inline[]{if(/\{\{/.test(value.replace(/\{\{(数值|引用):[^{}]+\}\}/g,'')))throw new Error('数值或引用标记不完整');const parts:Inline[]=[];const pattern=/\{\{(数值|引用):([^{}]+)\}\}/g;let start=0;for(const match of value.matchAll(pattern)){if(match.index!>start)parts.push({type:'text',text:value.slice(start,match.index)});const allowed=match[1]==='数值'?report.values:report.evidence;const found=allowed.find(r=>key(r)===match[2]);if(!found)throw new Error('数值或引用版本不属于这份报告：'+match[2]);parts.push({type:match[1]==='数值'?'value':'citation',ref:{id:found.id,revision:found.revision}});start=match.index!+match[0].length}if(start<value.length)parts.push({type:'text',text:value.slice(start)});return parts}
function InlineEditor({value,onChange,report,label}:{value:Inline[];onChange:(v:Inline[])=>void;report:ReportView;label:string}){
 const [draft,setDraft]=useState(()=>text(value)),[error,setError]=useState(''),area=useRef<HTMLTextAreaElement>(null)
 const change=(v:string)=>{setDraft(v);try{onChange(parse(v,report));setError('')}catch(e){setError(String(e))}}
 const insert=(v:string)=>{if(!v)return;const at=area.current?.selectionStart??draft.length;change(draft.slice(0,at)+v+draft.slice(at));area.current?.focus()}
 return <Field label={label}><Textarea ref={area} aria-label={label} value={draft} aria-invalid={!!error} rows={3} onChange={e=>change(e.target.value)}/><div className={s.chips}><Select aria-label={'插入数值到'+label} value="" onChange={e=>insert(e.target.value)}><option value="">插入数值…</option>{report.values.map(v=><option key={key(v)} value={`{{数值:${key(v)}}}`}>{v.metric} · {v.period} · {report.value_labels[key(v)]}</option>)}</Select><Select aria-label={'插入引用到'+label} value="" onChange={e=>insert(e.target.value)}><option value="">插入引用…</option>{report.evidence.map(e=><option key={key(e)} value={`{{引用:${key(e)}}}`}>{e.quote.slice(0,65)}</option>)}</Select></div>{error&&<InlineError>{error}</InlineError>}</Field>
}
export default function ReportEditor({report,onSaved,onClose}:{report:ReportView;onSaved:()=>void;onClose:()=>void}){
 const [doc,setDoc]=useState(()=>structuredClone(report.document)),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),editor=useRef<HTMLDivElement>(null)
 const change=(fn:(copy:typeof doc)=>void)=>setDoc(old=>{const copy=structuredClone(old);fn(copy);return copy})
 async function save(){if(editor.current?.querySelector('[aria-invalid="true"]')){setError('请先修正无效的数值或引用标记');return}setBusy(true);try{await api('/reports/'+doc.id+'/revisions',{operation_id:operation(),expected_revision:doc.revision,title:doc.title,summary:doc.summary,sections:doc.sections,gaps:doc.gaps,next_steps:doc.next_steps,reason});onSaved()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <div ref={editor}><Card className={s.followup}><h2>修订报告 · 基于版本 {doc.revision}</h2><Field label="报告标题"><Input value={doc.title} onChange={e=>change(c=>{c.title=e.target.value})}/></Field>
 {doc.summary.map((p,i)=><InlineEditor key={p.id} label={'摘要 '+(i+1)} value={p.inlines} report={report} onChange={v=>change(c=>{c.summary[i].inlines=v})}/>)}
 {doc.sections.map((sec,i)=><section key={sec.id}><Field label={'章节 '+(i+1)+' 标题'}><Input value={sec.title} onChange={e=>change(c=>{c.sections[i].title=e.target.value})}/></Field>{sec.blocks.map((block,j)=>block.type==='paragraph'?<InlineEditor key={block.id} label={sec.title+' 段落 '+(j+1)} value={block.inlines} report={report} onChange={v=>change(c=>{const b=c.sections[i].blocks[j];if(b.type==='paragraph')b.inlines=v})}/>:block.type==='table'?<details key={block.id}><summary>编辑表格 · {block.title}</summary>{block.rows.map((row,r)=>row.map((cell,col)=><InlineEditor key={`${r}-${col}`} label={`${block.title} 行 ${r+1} · ${block.columns[col]}`} value={cell} report={report} onChange={v=>change(c=>{const b=c.sections[i].blocks[j];if(b.type==='table')b.rows[r][col]=v})}/>) )}</details>:<details key={block.id}><summary>编辑图表引用 · {block.title}</summary>{block.series.map((series,k)=>series.values.map((ref,n)=><Field key={`${k}-${n}`} label={series.name+' · '+block.categories[n]}><Select value={ref?key(ref):''} onChange={e=>change(c=>{const b=c.sections[i].blocks[j];if(b.type==='chart'){const v=report.values.find(v=>key(v)===e.target.value);b.series[k].values[n]=v?{id:v.id,revision:v.revision}:null}})}><option value="">缺项</option>{report.values.filter(v=>v.unit===block.unit).map(v=><option key={key(v)} value={key(v)}>{v.metric} · {v.period} · {report.value_labels[key(v)]}</option>)}</Select></Field>))}</details>)}<Button size="sm" onClick={()=>change(c=>{c.sections[i].blocks.push({type:'paragraph',id:'paragraph-'+crypto.randomUUID(),inlines:[{type:'text',text:''}],assertions:[]})})}>添加段落</Button></section>)}
 <Button onClick={()=>change(c=>{c.sections.push({id:'section-'+crypto.randomUUID(),title:'新章节',blocks:[]})})}>添加章节</Button><Field label="限制与缺项（每行一项）"><Textarea value={doc.gaps.join('\n')} onChange={e=>change(c=>{c.gaps=e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="修订原因"><Input value={reason} onChange={e=>setReason(e.target.value)}/></Field>{error&&<InlineError>{error}</InlineError>}<div className={s.chips}><Button variant="primary" disabled={busy||!reason.trim()} onClick={save}>保存新修订并重新核验</Button><Button onClick={onClose}>取消编辑</Button></div><p className="sub">历史版本与已导出文件保持原样。文字中的数值和引用标记会保留准确版本。</p></Card></div>
}
