import {useEffect,useRef,useState} from 'react'
import {Link,useNavigate,useSearchParams} from 'react-router-dom'
import {useQueryClient} from '@tanstack/react-query'
import {useCompany} from '../../app/company'
import {api,operation,upload} from '../../lib/api'
import {Select,Textarea,Badge,Button,Card,CardHeader,EmptyState,Field,IconButton,Input,InlineError,Loading,Seg,Table,useToast} from '../../ui'
import {scopeQuery,localDateTime} from '../../workbench/ScopeBar'
import type {Subject} from '../../types/subject'
import {key,useData,Status} from '../../workbench/shared'
import {relativeTime} from '../../lib/format'
import type {Run} from '../../types/run'
import type {ResearchCase} from '../../types/research_case'
import type {SourceVersion} from '../../types/source_version'
import type {Ref} from '../../types/ref'
import type {NewsResearchDraft} from '../../types/lab_news_research_draft'
import type {CreateCase} from '../../types/create_case'
import s from './research.module.css'
import app from '../../app/app.module.css'
export function ResearchHome(){
  const {company,setCompany}=useCompany(),[params]=useSearchParams(),navigate=useNavigate(),client=useQueryClient(),{notify}=useToast()
  const [question,setQuestion]=useState(params.get('question')||''),[selected,setSelected]=useState<Ref[]>([]),[knowledge,setKnowledge]=useState<Ref[]>(()=>{const k=params.get('knowledge');if(!k)return [];const i=k.lastIndexOf('@');return [{id:k.slice(0,i),revision:Number(k.slice(i+1))}]})
  const [depth,setDepth]=useState<CreateCase['depth']>('standard'),[provider,setProvider]=useState<'codex'|'claude'|''>(''),[model,setModel]=useState('')
  const [type,setType]=useState<CreateCase['report_type']>('memo'),[asOf,setAsOf]=useState(params.get('as_of')||''),[search,setSearch]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [url,setUrl]=useState(''),[showUrl,setShowUrl]=useState(false),draftLoaded=useRef(''),[period,setPeriod]=useState(''),[subjects,setSubjects]=useState<string[]>(company?[company]:[])
  const {data:companies}=useData<Subject[]>('/subjects')
  const [attachments,setAttachments]=useState<Record<string,Pick<SourceVersion,'title'>>>({})
  const [recordSearch,setRecordSearch]=useState(''),[filter,setFilter]=useState('all')
  const {data:runs}=useData<Run[]>('/runs',5000)
  const runFor=(id:string)=>runs?.find(r=>r.case_id===id)
  const matches=(c:ResearchCase,kind:string)=>{const status=runFor(c.id)?.status;return kind==='all'||kind==='active'&&['running','queued'].includes(status||'')||kind==='attention'&&['waiting_user','failed','budget_exhausted'].includes(status||'')||kind==='completed'&&status==='completed'}
  useEffect(()=>{if(params.get('company'))setCompany(params.get('company')!)},[params,setCompany])
  useEffect(()=>{setSubjects(company?[company]:[])},[company])
  const {data:cases}=useData<ResearchCase[]>('/cases',5000),{data:sources}=useData<SourceVersion[]>('/sources?'+scopeQuery(subjects.length===1?subjects[0]:'',asOf))
  const {data:settings}=useData('/settings')
  useEffect(()=>{const id=params.get('news_draft');if(!id||draftLoaded.current===id)return;draftLoaded.current=id;api<NewsResearchDraft>('/lab/news/drafts/'+id).then(d=>{setCompany(d.company);setQuestion(d.question);setSelected(d.materials.map(m=>m.source));setKnowledge(d.knowledge)}).catch(e=>setError(String(e)))},[params])
  async function addFile(file:File){setBusy(true);try{const source=await upload('/sources/upload',file,company);setAttachments(p=>({...p,[key(source)]:{title:source.title}}));setSelected(p=>[...p.filter(r=>key(r)!==key(source)),{id:source.id,revision:source.revision}]);await client.invalidateQueries({predicate:q=>q.queryKey[0]==='v1'&&String(q.queryKey[1]).startsWith('/sources?')})}catch(e){setError(String(e))}finally{setBusy(false)}}
  async function addUrl(){setBusy(true);try{const source=await api<SourceVersion>('/sources/fetch',{operation_id:operation(),url,subjects:company?[company]:[]});setAttachments(p=>({...p,[key(source)]:{title:source.title}}));setSelected(p=>[...p.filter(r=>key(r)!==key(source)),{id:source.id,revision:source.revision}]);setUrl('');await client.invalidateQueries({predicate:q=>q.queryKey[0]==='v1'&&String(q.queryKey[1]).startsWith('/sources?')})}catch(e){setError(String(e))}finally{setBusy(false)}}
  const submitting=useRef(false),command=useRef({fingerprint:'',id:operation()})
  async function submit(start:boolean){if(submitting.current)return;submitting.current=true;setBusy(true);setError('');try{const request:CreateCase={operation_id:operation(),question,scope:{subjects,period,mode:asOf?'historical':'live',as_of:asOf?new Date(asOf).toISOString():null,allow_public_search:asOf?false:search,proof_level:'proven'},sources:selected,knowledge,depth,report_type:type,agent_provider:provider||null,model:model||null,news_draft_id:params.get('news_draft'),parent_case_id:params.get('parent')};const fingerprint=JSON.stringify({...request,operation_id:''});if(fingerprint!==command.current.fingerprint)command.current={fingerprint,id:operation()};request.operation_id=command.current.id;const c=await api<ResearchCase>('/cases',request);if(start){try{await api('/cases/'+c.id+'/runs',{operation_id:operation(),expected_revision:c.input.revision})}catch(e){notify('问题已保存：'+String(e),'danger')}}await client.invalidateQueries();navigate('/research/'+c.id)}catch(e){setError(String(e))}finally{setBusy(false);submitting.current=false}}
  return <div className={app.page} data-testid="research-home"><header className={s.hero}><h1 className="display">从一个问题开始</h1><p className="sub">描述你想弄清楚的事，附上材料。系统固定范围、研究、核验，最后交付可核对的判断。</p></header>
    <Card className={s.composer}><Textarea aria-label="研究问题" className={s.question} style={{border:0,padding:0,resize:'none',background:'transparent',minHeight:84}} placeholder="例如：对比 PDD 两期的收入、经营利润及经营利润率。仅使用原始披露，区分原文解释与资料缺口。" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)&&!e.nativeEvent.isComposing&&!busy&&question.trim()){e.preventDefault();submit(true)}}}/>
      {params.has('news_draft')&&<Badge tone="warn">资讯实验草稿 · 评分不会作为研究核验结果</Badge>}
      <div className={s.scopeLine}><span>公司</span>{subjects.map(id=><Badge key={id}>{companies?.find(c=>c.id===id)?.name||id}</Badge>)}{!subjects.length&&<span>未限定</span>}<label>期间 <Input placeholder="例如 2025Q2 / 2024Q2" aria-label="研究期间" value={period} onChange={e=>setPeriod(e.target.value)} style={{width:180,height:26}}/></label></div>
      {selected.length>0&&<div className={s.attachments}>{selected.map(ref=>{const source=sources?.find(v=>key(v)===key(ref))||attachments[key(ref)];return <div className={s.attachment} key={key(ref)}><span className={s.fileIcon}>文</span><span><b>{source?.title||'已固定的原件'}</b><small>修订 {ref.revision} · 已保存</small></span><IconButton icon="x" label={'移除材料 '+(source?.title||ref.id)} plain disabled={busy} onClick={()=>setSelected(p=>p.filter(v=>key(v)!==key(ref)))}/></div>})}</div>}
      {showUrl&&<div className={s.urlRow}><Input aria-label="原件网址" placeholder="公开原件网址" value={url} onChange={e=>setUrl(e.target.value)}/><Button size="sm" disabled={busy||!url} onClick={addUrl}>获取原件</Button></div>}
      <details><summary>选择已有材料 · 已选 {selected.length} 份</summary><div className={s.list}>{sources?.filter(source=>!subjects.length||source.subjects.some(sub=>subjects.includes(sub))).map(source=><label key={key(source)}><input type="checkbox" checked={selected.some(r=>key(r)===key(source))} onChange={e=>setSelected(p=>e.target.checked?[...p,{id:source.id,revision:source.revision}]:p.filter(r=>key(r)!==key(source)))}/>{source.title} <small>修订 {source.revision}</small></label>)}{!sources?.length&&<p className="muted">还没有原件，可上传文件或获取网址。</p>}</div></details>
      <div className={s.execRow}><label>深度<Select aria-label="研究深度" value={depth} onChange={e=>setDepth(e.target.value as CreateCase['depth'])}><option value="interactive">交互</option><option value="standard">标准</option><option value="deep">深度</option></Select></label><label>报告<Select value={type} onChange={e=>setType(e.target.value as CreateCase['report_type'])}><option value="memo">研究备忘</option><option value="earnings">财报变化</option><option value="company">公司研究</option><option value="industry">产业研究</option></Select></label><label>Agent<Select aria-label="Agent" value={provider} onChange={e=>setProvider(e.target.value as typeof provider)}><option value="">本机设置</option><option value="codex">Codex</option><option value="claude">Claude</option></Select></label><label>模型<Input aria-label="模型" placeholder="沿用本机默认" value={model} onChange={e=>setModel(e.target.value)}/></label></div>
      <details><summary>资料与时点范围</summary><p>研究主体（可多选）</p>{companies?.map(c=><label key={c.id}><input type="checkbox" checked={subjects.includes(c.id)} onChange={e=>setSubjects(p=>e.target.checked?[...p,c.id]:p.filter(id=>id!==c.id))}/>{c.name}</label>)}<Field label="历史截止时间（留空为当前研究）"><Input aria-label="历史截止时间" type="datetime-local" value={localDateTime(asOf)} onChange={e=>setAsOf(e.target.value)}/></Field><label><input type="checkbox" checked={!asOf&&search} disabled={!!asOf} onChange={e=>setSearch(e.target.checked)}/>允许获取公开原件</label>{asOf&&<p className="sub">历史研究只使用具有可得时间证明的固定材料。</p>}</details>
      {settings?.budgets?.[depth||'standard']&&<p className="sub">活动时间 {Math.round(settings.budgets[depth||'standard'].active_seconds/60)} 分钟 · 工具 {settings.budgets[depth||'standard'].tool_calls} 次 · 保留 10% 收尾额度，耗尽后可显式继续。</p>}
      {error&&<InlineError>{error}</InlineError>}<div className={s.submitRow}><label className={s.attach}>＋ 添加原件<input aria-label="研究附件" type="file" multiple accept=".pdf,.txt,.md,.html" disabled={busy} onChange={async e=>{for(const f of Array.from(e.target.files||[]))await addFile(f);e.target.value=''}}/></label><Button size="sm" variant="ghost" onClick={()=>setShowUrl(v=>!v)}>从网址获取</Button><span className="muted" style={{fontSize:12}}>PDF / HTML / TXT / MD</span><span style={{flex:1}}/>{busy&&<Loading>正在保存…</Loading>}<Button disabled={busy||!question.trim()} onClick={()=>submit(false)}>保存问题</Button><Button variant="primary" icon="flask" disabled={busy||!question.trim()} onClick={()=>submit(true)}>开始研究</Button></div>
    </Card><Card className={s.records}><CardHeader title="研究记录"><Seg label="筛选研究记录" value={filter} onChange={setFilter} options={[['all','全部'],['active','进行中'],['attention','需要关注'],['completed','已完成']].map(([value,label])=>({value,label:label+' '+(cases||[]).filter(c=>matches(c,value)).length}))}/><Input aria-label="搜索研究记录" type="search" placeholder="搜索问题、公司…" value={recordSearch} onChange={e=>setRecordSearch(e.target.value)} style={{marginLeft:'auto',width:220,height:30}}/></CardHeader>
    {!!cases?.filter(c=>matches(c,filter)&&(c.title+' '+c.input.scope.subjects.join(' ')).toLowerCase().includes(recordSearch.toLowerCase())).length?<Table><thead><tr><th style={{width:'44%'}}>问题</th><th>对象 · 期间</th><th>执行状态</th><th>输入版本</th><th>更新</th></tr></thead><tbody>{cases!.filter(c=>matches(c,filter)&&(c.title+' '+c.input.scope.subjects.join(' ')).toLowerCase().includes(recordSearch.toLowerCase())).map(c=><tr key={c.id} className={s.recordRow}><td><Link to={'/research/'+c.id} className={s.recordLink}>{c.title}</Link></td><td className="sub">{c.input.scope.subjects.join(' · ')||'未限定'}{c.input.scope.period?' · '+c.input.scope.period:''}</td><td>{runFor(c.id)?<Status value={runFor(c.id)!.status}/>:<Badge>已保存问题</Badge>}</td><td className="mono muted">r{c.input.revision}</td><td className="muted">{relativeTime(c.updated_at)}</td></tr>)}</tbody></Table>:<EmptyState>{cases?.length?'没有符合筛选条件的研究。':'第一项研究会保存在这里。试着提出你最近想弄清楚的一个问题。'}</EmptyState>}</Card>
  </div>
}
